---
driver:
  name: gce
  project: protean-bus-122701
  zone: us-east1-c
  email: jalexspringer@gmail.com
  tags:
    - test-kitchen
  service_account_scopes:
    - devstorage.read_write
    - userinfo.email

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  username: chefuser
  ssh_key: /home/vagrant/.ssh/google_compute_engine

platforms:
  - name: ubuntu-AAR
    driver:
      image_project: ubuntu-os-cloud
      image_name: ubuntu-1204-precise-v20170330

suites:
  - name: default
    run_list:
      - recipe[AAR::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
